[package]
name = "exia"
version = "0.1.0"
edition = "2024"

[dependencies]
default-net = "0.22.0"
ipnet = "2.11.0"
pnet = "0.35.0"
pnet_datalink = "0.35.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = { version = "1.17.0", features = ["v4"] }
