[package]
name = "exia"
version = "0.1.0"
edition = "2024"

[dependencies]
pnet_datalink = "0.35.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = { version = "1.17.0", features = ["v4"] }
